//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OutlookPlugin.rc
//
#define IDCANCEL2                       3
#define IDHELPD_WELCOME                 9
#define IDD_ABOUTBOX                    100
#define IDD_SYNC_FORM                   101
#define IDM_NULLMENU                    127
#define IDR_NULLMENU                    127
#define IDR_MAINFRAME                   128
#define IDS_SYNCTYPE1                   129
#define IDS_SYNCTYPE2                   130
#define IDD_FORM_LEFT                   131
#define IDS_SYNCTYPE3                   131
#define IDD_ACCOUNT                     132
#define IDS_ACCOUNT_SETTINGS            132
#define IDD_SYNC                        133
#define IDS_ACCOUNT_URL                 133
#define IDD_CONTACTS                    134
#define IDS_ACCOUNT_USERNAME            134
#define IDD_CALENDAR                    135
#define IDS_ACCOUNT_PASSWORD            135
#define IDD_TASKS                       136
#define IDS_ACCOUNT_USEPROXY            136
#define IDD_NOTES                       137
#define IDS_ACCOUNT_PROXY_AUTH          137
#define IDS_ACCOUNT_PROXY_USER          138
#define IDD_LOG                         139
#define IDS_ACCOUNT_PROXY_PASS          139
#define IDD_DIALOG1                     140
#define IDD_FULLSYNC                    140
#define IDS_OK                          140
#define IDB_BITMAP1                     141
#define IDS_CANCEL                      141
#define IDB_CHECKBOX                    142
#define IDS_ACCOUNT                     142
#define IDS_OUTLOOK_FOLDER              143
#define IDR_241                         144
#define IDS_INCLUDE_SUBFOLDERS          144
#define IDS_SHARED                      145
#define IDS_SELECT_FOLDER               146
#define IDS_REMOTE_NAME                 147
#define IDS_SYNC                        148
#define IDS_ENABLED                     149
#define IDS_ADVANCED_CALENDAR           150
#define IDS_DATA_FORMAT                 151
#define IDD_PROXY                       151
#define IDS_USE_SIF                     152
#define IDD_PICTURES                    152
#define IDS_ENCRYPTION                  153
#define IDD_FORMVIEW                    153
#define IDS_ADVANCED_CONTACTS           154
#define IDI_ARROWS32A                   155
#define IDS_DOWNLOAD_ONLY               155
#define IDI_ARROWS32B                   156
#define IDS_UPLOAD_ONLY                 156
#define IDS_FULLSYNC_PERFORM            158
#define IDS_CONTACTS                    159
#define IDS_CALENDAR                    160
#define IDS_NOTES                       161
#define IDS_TASKS                       162
#define IDI_CANCEL                      162
#define IDS_SYNCHRONIZE                 163
#define IDI_CONTACTS                    163
#define IDS_LOG_LEVEL                   164
#define IDI_CALENDAR                    164
#define IDS_LOG_NONE                    165
#define IDI_TASKS                       165
#define IDS_LOG_INFO                    166
#define IDI_NOTES                       166
#define IDS_LOG_DEBUG                   167
#define IDI_ARROWS32C                   167
#define IDS_ADVANCED_NOTES              168
#define IDI_ARROWS32D                   168
#define IDS_ADVANCED_TASKS              169
#define IDI_CONTACTS_GREY               169
#define IDS_ERROR_CANNOT_CHANGE_SETTINGS 170
#define IDI_CALENDAR_GREY               170
#define IDS_ERROR_SET_URL               171
#define IDI_TASKS_GREY                  171
#define IDS_ERROR_SET_USERNAME          172
#define IDI_NOTES_GREY                  172
#define IDS_ERROR_SET_PASSWORD          173
#define IDS_ERROR_PROXY_USERNAME        174
#define IDS_ERROR_PROXY_PASSWORD        175
#define IDS_ERROR_SET_REMOTE_NAME       176
#define IDS_MINUTES                     177
#define IDS_SCHEDULER_EVERY             178
#define IDS_EXTRA_SETTINGS              179
#define IDS_CODE_NOSOURCE_10            180
#define IDS_CODE_SYNC_STOPPED           181
#define IDS_CODE_AUTH_EXPIRED_402       182
#define IDS_CODE_NOTFOUND_404           183
#define IDS_CODE_INVALID_CREDENTIALS_401 184
#define IDS_CODE_ERROR_CONNECT_2001     185
#define IDS_CODE_ERROR_READING_CONTENT_2002 186
#define IDS_CODE_SERVER_NOT_FOUND_2003  187
#define IDS_CODE_INTERNET_CONNECTION_MISSING_2005 188
#define IDS_CODE_NETWORK_ERROR_2007     189
#define IDS_ERROR_SYNC_NOT_COMPLETED    191
#define IDS_TEXT_APPOINTMENTS           192
#define IDS_TEXT_CONTACTS               193
#define IDS_TEXT_NOTES                  194
#define IDS_TEXT_TASKS                  195
#define IDS_TEXT_SENDING                196
#define IDS_TEXT_RECEIVING              197
#define IDS_TEXT_SYNC_ENDED             198
#define IDS_MAINBUT_SYNCHRONIZE         199
#define IDS_MAINBUT_CANCEL              200
#define IDS_TEXT_STARTING_SYNC          201
#define IDS_TEXT_SYNC_CANCELED          202
#define IDS_LEFTVIEW_ACCOUNT            203
#define IDS_LEFTVIEW_SYNCHRONIZATION    204
#define IDS_HOURS                       205
#define IDS_SCHEDULER_PLEASE_SET_VALUE  206
#define IDS_SCHEDULER_MIN_VALUE_IS      207
#define IDS_SCHEDULER_MAX_VALUE_IS      208
#define IDS_SCHEDULER_CANNOT_SCHEDULE   209
#define IDS_LEFTVIEW_CONTACTS           210
#define IDS_LEFTVIEW_CALENDAR           211
#define IDS_LEFTVIEW_TASKS              212
#define IDS_LEFTVIEW_NOTES              213
#define IDS_CLOSE                       214
#define IDS_SCHEDULER                   215
#define IDS_LEFTVIEW_LOG                216
#define IDS_DAYS                        217
#define IDS_MSG_CLOSE_SYNC_IN_PROGRESS  218
#define IDS_UPDATE_REQUIRED             219
#define IDS_ABOUT_COPYRIGHT             220
#define IDS_UPDATES                     220
#define IDS_TEXT_SYNC_ALREADY_RUNNING   221
#define IDS_SYNC_ABORTED_AVOID_FULLSYNC 222
#define IDS_TEXT_SYNC_IN_PROGRESS       223
#define IDS_DETAILS                     224
#define IDS_SYNC_SETTINGS               225
#define IDS_APPLY                       226
#define IDS_ERROR_SYNC_TERMINATED       227
#define IDS_TEXT_CANCELING_SYNC         228
#define IDS_MAIN_PRESS_TO_SYNC          229
#define IDS_MAIN_PRESS_TO_CANCEL        230
#define IDS_DONE                        231
#define IDS_SERVER                      232
#define IDS_PROXY_SETTINGS              233
#define IDS_PROXY_SETTINGS2             234
#define IDS_ITEMS                       235
#define IDS_SYNC_SYNCHRONIZE_EVERY      236
#define IDS_SECURITY                    237
#define IDS_SYNC_ENABLE_ENCRYPTION      238
#define IDS_CONTACTS_DETAILS            239
#define IDS_SYNC_DIRECTION              240
#define IDS_CONTACTS_FOLDER             241
#define IDS_CURRENT                     242
#define IDS_ADVANCED                    243
#define IDS_CALENDAR_DETAILS            244
#define IDS_CALENDAR_FOLDER             245
#define IDS_USE_VCAL                    246
#define IDS_TASKS_DETAILS               247
#define IDS_TASKS_FOLDER                248
#define IDS_NOTES_DETAILS               249
#define IDB_BITMAP2                     249
#define IDS_NOTES_FOLDER                250
#define IDB_BITMAP3                     250
#define IDS_RECOVER_PERFORMS            251
#define IDS_DIRECTION                   252
#define IDB_BITMAP4                     252
#define IDS_FULLSYNC_SYNCTYPE2          253
#define IDS_FULLSYNC_SYNCTYPE1          254
#define IDS_FULLSYNC_SYNCTYPE3          255
#define IDI_LOGO                        255
#define IDS_RECOVER                     256
#define IDB_BK_DARK                     256
#define IDS_LOGGING                     257
#define IDB_BK_LIGHT                    257
#define IDS_NOT_SYNCHRONIZED            258
#define IDB_BITMAP6                     258
#define IDB_BK_BLUE                     258
#define IDS_FUNAMBOL_LINK               259
#define IDI_SYNC                        259
#define IDS_SYNCHRONIZED                260
#define IDI_ACCOUNT                     260
#define IDS_AT                          261
#define IDS_MAIN_CALENDAR               262
#define IDI_SYNC_ALL                    262
#define IDS_MAIN_CONTACTS               263
#define IDI_ALERT                       263
#define IDS_MAIN_TASKS                  264
#define IDI_OK                          264
#define IDI_COMPLETE                    264
#define IDS_MAIN_NOTES                  265
#define IDI_ICON1                       265
#define IDS_ERROR_SET_CONNECTION        266
#define IDB_BK_DARK_BLUE                266
#define IDI_SYNC_ALL_BLUE               266
#define IDS_ABOUT_TITLE                 267
#define IDB_LEFT_BUTTON                 267
#define IDI_PICTURES                    267
#define IDS_MAIN_LAST_SYNC_FAILED       268
#define IDI_NOTES_GREY1                 268
#define IDI_PICTURES_GREY               268
#define IDS_MAIN_LAST_SYNC_CANCELED     269
#define IDB_SEPARATOR                   269
#define IDS_LOG_SEND                    270
#define IDD_UPDATE                      271
#define IDS_LOG_VIEWLOG                 271
#define IDS_UNEXPECTED_EXCEPTION        272
#define IDS_SYNCALL                     273
#define IDD_POPUP                       273
#define IDI_ACCOUNT_GREY                273
#define IDS_CODE_DROPPED_ITEMS          274
#define IDI_SYNC_GREY                   274
#define IDS_TEXT_CHECKING               275
#define IDS_FINISHED_SENDING            276
#define IDS_GUIDE_LINK                  277
#define IDS_ERR_SERVER_TIMOUT           278
#define IDI_UPDATE_GREY                 278
#define IDS_CODE_SERVER_BUSY            279
#define IDS_CODE_SERVER_BUSY_SYNC       280
#define IDS_CODE_SERVER_ERROR_2052      281
#define IDS_CODE_DROPPED_ITEMS_SERVER   282
#define IDS_CODE_NO_SOURCES             283
#define IDD_UPGRADING                   283
#define IDS_HOUR                        284
#define IDS_CODE_FORBIDDEN_403          285
#define IDD_WELCOME                     285
#define IDS_LOG_DETAILS                 286
#define IDS_WELCOME_MESSAGE             287
#define IDS_WELCOME                     287
#define IDS_CODE_FOLDER_PATH_NOT_FOUND  288
#define IDS_PLEASE_WAIT                 289
#define IDS_WELCOME_MESSAGE2            290
#define IDS_UPGRADING                   290
#define IDS_USE_VTODO                   291
#define IDS_USE_VNOTE                   292
#define IDS_EVENT_FILTER                293
#define IDS_SYNC_PAST_EVENTS            294
#define IDS_DATE_FILTER_NONE            295
#define IDS_DATE_FILTER_LAST_WEEK       296
#define IDS_DATE_FILTER_LAST_MONTH      297
#define IDS_DATE_FILTER_LAST_3_MONTHS   298
#define IDS_DATE_FILTER_LAST_6_MONTHS   299
#define IDS_STRING300                   300
#define IDS_LOG_EDIT_NUM_LOGS           300
#define IDS_DATE_FILTER_LAST_2_WEEKS    302
#define IDS_PICTURES                    303
#define IDS_ADVANCED_PICTURES           304
#define IDS_TEXT_PICTURES               305
#define IDS_LEFTVIEW_PICTURES           306
#define IDS_PICTURES_DETAILS            307
#define IDS_PICTURES_FOLDER             308
#define IDS_MAIN_PICTURES               309
#define IDS_WARN_ONE_WAY_FROM_SERVER_TO_TWO_WAY 310
#define IDS_WARN_ONE_WAY_FROM_CLIENT_TO_TWO_WAY 311
#define IDS_STRING312                   312
#define IDS_LOG_EDIT_LOG_SIZE           312
#define IDS_SELECT_PICTURES_FOLDER      313
#define IDS_PICTURES_OMA_FILEDATA       314
#define IDS_PICTURES_RAW_FILEDATA       315
#define IDS_ENDING_SYNC                 316
#define IDS_HOURS2                      400
#define IDS_DATE_FILTER_ALL             401
#define IDS_REQUIRE_OUTLOOK_OPEN        410
#define IDS_USE_VCARD                   411
#define IDS_UNCHECK_SHARED              412
#define IDS_UP_MESSAGE_SKIPPED          413
#define IDS_BUT_NOW_LATER_SKIP          414
#define IDS_BUT_NOW_LATER               415
#define IDS_UP_MESSAGE                  416
#define IDS_UP_MANDATORY_MESSAGE        417
#define IDS_BUT_NOW_EXIT                418
#define IDS_UP_MANDATORY_MESSAGE_EXIT   419
#define IDS_UPDATE_SOFTWARE             420
#define IDS_UPDATE_SOFTWARE_TITLE       421
#define IDB_POWERED_BY                  422
#define IDC_TREE1                       1001
#define IDC_SCHEDULER_SPIN              1002
#define IDC_EDIT2                       1003
#define IDC_ACCOUNT_EDIT_USERNAME       1004
#define IDC_EDIT3                       1005
#define IDC_ACCOUNT_EDIT_URL            1006
#define IDC_EDIT4                       1007
#define IDC_ACCOUNT_EDIT_PASSWORD       1008
#define IDC_CHECK1                      1009
#define IDC_FULLSYNC_CHECK_CONTACTS     1010
#define IDC_SYNC_CHECK_ENCRYPTION       1011
#define IDC_CALENDAR_STATIC_FILTER      1012
#define IDC_CALENDAR_CHECK_SHARED       1013
#define IDC_CHECK2                      1014
#define IDC_FULLSYNC_CHECK_CALENDAR     1015
#define IDC_SYNC_CHECK_OUTLOOK_OPEN     1016
#define IDC_EDIT5                       1017
#define IDC_CHECK3                      1018
#define IDC_FULLSYNC_CHECK_TASKS        1019
#define IDC_EDIT6                       1020
#define IDC_CHECK4                      1021
#define IDC_ACCOUNT_PROXY_PASS          1022
#define IDC_FULLSYNC_CHECK_NOTES        1023
#define IDC_BUTTON1                     1024
#define IDC_TASKS_OK                    1025
#define IDC_MAIN_BUT_SYNC               1026
#define IDC_SYNC_APPLY                  1027
#define IDC_LOG_VIEWLOG                 1028
#define IDC_ACCOUNT_BUT_PROXY           1029
#define IDC_BUTTON2                     1030
#define IDC_TASKS_CANCEL                1031
#define IDC_SYNC_DETAILS                1032
#define IDC_LOG_VIEWLOG2                1033
#define IDC_LOG_VIEWPATH                1034
#define IDC_COMBO1                      1035
#define IDC_SCHEDULER_COMBO_VALUE_TYPE  1036
#define IDC_BUTTON7                     1037
#define IDC_BUTTON3                     1038
#define IDC_SYNC_BUT_CONTACTS           1039
#define IDC_MAIN_BUT_START              1040
#define IDC_EDIT1                       1041
#define IDC_TASKS_EDIT_FOLDER           1042
#define IDC_SCHEDULER_VALUE             1043
#define IDC_WELCOME_MESSAGE1            1044
#define IDC_SYNC_COMBO_CALENDAR         1045
#define IDC_SCHEDULER_COMBO_VALUE       1046
#define IDC_BUTTON4                     1047
#define IDC_RADIO1                      1048
#define IDC_SYNC_BUT_CALENDAR           1049
#define IDC_LOG_RADIO_NONE              1050
#define IDC_FULLSYNC_RADIO1             1051
#define IDC_COMBO3                      1052
#define IDC_RADIO2                      1053
#define IDC_SPIN1                       1054
#define IDC_SYNC_COMBO_TASKS            1055
#define IDC_LOG_RADIO_INFO              1056
#define IDC_SYNC_STATIC_NOTES           1057
#define IDC_FULLSYNC_RADIO2             1058
#define IDC_FULLSYNC_RADIO4             1059
#define IDC_BUTTON5                     1060
#define IDC_LIST1                       1061
#define IDC_RADIO3                      1062
#define IDC_SYNC_BUT_TASKS              1063
#define IDC_LOG_RADIO_DEBUG             1064
#define IDC_FULLSYNC_RADIO3             1065
#define IDC_LEFT_LIST                   1066
#define IDC_COMBO4                      1068
#define IDC_ACCOUNT_STATIC_ACCOUNTSETTINGS 1069
#define IDC_SYNC_COMBO_NOTES            1070
#define IDC_LOG_SPIN_NUM_LOGS           1071
#define IDC_LOG_EDIT_NUM_LOGS_SPIN      1072
#define IDC_BUTTON6                     1073
#define IDC_ACCOUNT_BUTOK               1074
#define IDC_SYNC_BUT_NOTES              1075
#define IDC_LOG_SPIN_LOG_SIZE           1076
#define IDC_LOG_EDIT_LOG_SIZE_SPIN      1077
#define IDC_ACCOUNT_STATIC_USERNAME     1078
#define IDC_SCHEDULER_SPIN2             1079
#define IDC_CALENDAR_COMBO_SYNCTYPE     1080
#define IDC_CALENDAR_EDIT_FOLDER        1081
#define IDC_CALENDAR_CHECK_INCLUDE      1082
#define IDC_CALENDAR_BUT_SELECT         1083
#define IDC_CALENDAR_EDIT_REMOTE        1084
#define IDC_CALENDAR_RADIO_SIF          1085
#define IDC_CALENDAR_RADIO_VCARD        1087
#define IDC_CALENDAR_COMBO_FILTER       1088
#define IDC_LOG_EDIT_LOG_SIZE           1090
#define IDC_CONTACTS_COMBO_SYNCTYPE     1091
#define IDC_CONTACTS_EDIT_FOLDER        1092
#define IDC_CONTACTS_CHECK_INCLUDE      1093
#define IDC_CONTACTS_BUT_FOLDER         1094
#define IDC_CONTACTS_EDIT_REMOTE        1095
#define IDC_CONTACTS_RADIO_SIF          1096
#define IDC_CONTACTS_RADIO_VCARD        1097
#define IDC_NOTES_CHECK_ENABLED         1098
#define IDC_NOTES_COMBO_SYNCTYPE        1099
#define IDC_NOTES_EDIT_FOLDER           1100
#define IDC_NOTES_CHECK_INCLUDE         1101
#define IDC_NOTES_BUT_SELECT            1102
#define IDC_NOTES_EDIT_REMOTE           1103
#define IDC_NOTES_RADIO_SIF             1104
#define IDC_NOTES_RADIO_VCARD           1105
#define IDC_TASKS_COMBO_SYNCTYPE        1106
#define IDC_TASKS_CHECK_INCLUDE         1107
#define IDC_TASKS_BUT_SELECT            1108
#define IDC_TASKS_EDIT_REMOTE           1109
#define IDC_TASKS_RADIO_SIF             1110
#define IDC_TASKS_RADIO_VCARD           1111
#define IDC_SCHEDULER_CHECK_ENABLED     1112
#define IDC_SYNC_CHECK_CONTACTS         1113
#define IDC_SYNC_CHECK_CALENDAR         1114
#define IDC_SYNC_CHECK_TASKS            1115
#define IDC_SYNC_CHECK_NOTES            1116
#define IDC_SYNC_COMBO_CONTACTS         1117
#define IDC_ACCOUNT_BUT_CANCEL          1118
#define IDC_CALENDAR_BUTOK              1119
#define IDC_CALENDAR_BUTCANCEL          1120
#define IDC_CONTACTS_BUTOK              1121
#define IDC_CONTACTS_BUTCANCEL          1122
#define IDC_LOG_BUTOK                   1123
#define IDC_LOG_OK                      1124
#define IDC_LOG_CANCEL                  1125
#define IDC_NOTES_OK                    1126
#define IDC_NOTES_CANCEL                1127
#define IDC_SYNC_OK                     1128
#define IDC_SYNC_CANCEL                 1129
#define IDC_COMBOBOXEX1                 1130
#define IDC_LIST2                       1131
#define IDC_SYNC_STATIC_SETTINGS        1132
#define IDC_TASKS_STATIC_DATAFORMAT     1133
#define IDC_CALENDAR_STATIC_DATAFORMAT  1134
#define IDC_NOTES_STATIC_DATAFORMAT     1135
#define IDC_CONTACTS_STATIC_DATAFORMAT  1136
#define IDC_NOTES_STATIC_DATAFORMAT2    1137
#define IDC_NOTES_STATIC_DATAFORMAT3    1138
#define IDC_CONTACTS_DATA_FORMAT        1139
#define IDC_SYNC_PROGRESS_CONTACTS      1140
#define IDC_SYNC_PROGRESS_CALENDAR      1141
#define IDC_SYNC_PROGRESS_NOTES         1142
#define IDC_SYNC_PROGRESS_TASKS         1143
#define IDC_SYNC_STATIC_CONTACTS        1144
#define IDC_SYNC_STATIC_CALENDAR        1145
#define IDC_SYNC_STATIC_TASKS           1146
#define IDC_SYNC_ICON_CONTACTS          1147
#define IDC_SYNC_ICON_CALENDAR          1148
#define IDC_SYNC_ICON_TASKS             1149
#define IDC_SYNC_ICON_NOTES             1150
#define IDC_SCROLLBAR1                  1151
#define IDC_SYNC_PROGRESS_TOTAL         1152
#define IDC_SYNC_STATIC_TOTAL           1153
#define IDC_SYNC_ICON_TOTAL             1154
#define IDC_NOTES_ADVANCED              1155
#define IDC_ACCOUNT_STATIC_URL          1156
#define IDC_CALENDAR_STATIC_FOLDER      1157
#define IDC_CALENDAR_STATIC_REMOTE      1158
#define IDC_CALENDAR_STATIC_REMOTE2     1159
#define IDC_CONTACTS_STATIC_FOLDER      1160
#define IDC_CALENDAR_STATIC_REMOTE3     1161
#define IDC_CONTACTS_STATIC_REMOTE      1162
#define IDC_CALENDAR_STATIC_REMOTE4     1163
#define IDC_NOTES_STATIC_SYNCTYPE       1164
#define IDC_NOTES_STATIC_FOLDER         1165
#define IDC_NOTES_STATIC_REMOTE         1166
#define IDC_NOTES_STATIC_SIF            1167
#define IDC_TASKS_STATIC_SIF            1168
#define IDC_TASKS_STATIC_FOLDER         1169
#define IDC_TASKS_STATIC_REMOTE         1170
#define IDC_ABOUT_MAIN                  1171
#define IDC_ACCOUNT_APPLY               1172
#define IDC_ABOUT_LICENCE               1173
#define IDC_ABOUT_COPYRIGHT             1174
#define IDC_LOG_APPLY                   1175
#define IDC_ABOUT_COPYRIGHT2            1176
#define IDC_ACCOUNT_STATIC_PASSWORD     1177
#define IDC_FULLSYNC_GROUP_DIRECTION    1178
#define IDC_LOG_GROUP_LOGLEVEL          1179
#define IDC_FULLSYNC_STATIC_RECOVER     1180
#define IDC_LOG_GROUP_LOGLEVEL2         1181
#define IDC_LOG_GROUP_LOGDETAILS        1182
#define IDC_FULLSYNC_DIRECTION          1183
#define IDC_FULLSYNC_GROUP_ITEMS        1184
#define IDC_PROXY_ENABLE                1185
#define IDC_PROXY_AUTH                  1186
#define IDC_PROXY_EDIT_USER             1187
#define IDC_PROXY_EDIT_PASS             1188
#define IDC_PROXY_STATIC_USER           1189
#define IDC_PROXY_STATIC_PASSWORD       1190
#define IDC_ACCOUNT_GROUP_SERVER        1191
#define IDC_SCHEDULER_GROUP             1192
#define IDC_SYNC_GROUP_ITEMS            1193
#define IDC_SYNC_GROUP_SECURITY         1194
#define IDC_SECURITY_GROUP              1194
#define IDC_SYNC_GROUP_SCHEDULE         1195
#define IDC_CONTACTS_GROUP_DIRECTION    1196
#define IDC_CONTACTS_GROUP_FOLDER       1197
#define IDC_CONTACTS_GROUP_ADVANCED     1198
#define IDC_CALENDAR_GROUP_DIRECTION    1199
#define IDC_CALENDAR_GROUP_FOLDER       1200
#define IDC_CALENDAR_GROUP_ADVANCED     1201
#define IDC_NOTES_GROUP_DIRECTION       1202
#define IDC_CALENDAR_GROUP_FILTER       1203
#define IDC_NOTES_GROUP_FOLDER          1204
#define IDC_NOTES_GROUP_ADVANCED        1205
#define IDC_TASKS_GROUP_DIRECTION       1206
#define IDC_TASKS_GROUP_FOLDER          1207
#define IDC_TASKS_ADVANCED              1208
#define IDC_MAIN_MSG_PRESS              1209
#define IDC_MAIN_ICON_CONTACTS          1210
#define IDC_MAIN_ICON_CALENDAR          1211
#define IDC_MAIN_ICON_TASKS             1212
#define IDC_MAIN_ICON_NOTES             1213
#define IDC_MAIN_STATIC_CONTACTS        1214
#define IDC_MAIN_STATIC_STATUS_CONTACTS 1215
#define IDC_MAIN_STATIC_CALENDAR        1216
#define IDC_MAIN_STATIC_STATUS_CALENDAR 1217
#define IDC_MAIN_STATIC_TASKS           1218
#define IDC_MAIN_STATIC_STATUS_TASKS    1219
#define IDC_MAIN_STATIC_STATUS_NOTES    1220
#define IDC_MAIN_STATIC_NOTES           1221
#define IDC_MAIN_GROUP_SYNC             1222
#define IDC_MAIN_ICON_PICTURES          1223
#define IDC_MAIN_GROUP_SOURCES          1224
#define IDC_MAIN_STATIC_STATUS_PICTURES 1225
#define IDC_MAIN_STATIC_PICTURES        1226
#define IDC_MAIN_LINK_CALENDAR          1227
#define IDC_ABOUT_LINK                  1228
#define IDC_MAIN_LINK_NOTES             1229
#define IDC_MAIN_LINK_CONTACTS          1230
#define IDC_MAIN_LINK_TASKS             1231
#define IDC_STATIC1                     1232
#define IDC_UPDATE_STATIC_CURRENT       1233
#define IDC_MAIN_ICON_STATUS_CONTACTS   1234
#define IDC_MAIN_ICON_STATUS_CALENDAR   1235
#define IDC_MAIN_ICON_STATUS_TASKS      1236
#define IDC_MAIN_ICON_STATUS_NOTES      1237
#define IDC_MAIN_ICON_STATUS_SYNC       1238
#define IDC_MAIN_BK_SYNC                1239
#define IDC_MAIN_BK_SYNC2               1240
#define IDC_MAIN_BK_CONTACTS            1241
#define IDC_MAIN_BK_CONTACTS2           1242
#define IDC_MAIN_BK_CALENDAR            1243
#define IDC_MAIN_BK_TASKS               1244
#define IDC_RECT2                       1245
#define IDC_MAIN_BK_CALENDAR3           1246
#define IDC_MAIN_BK_NOTES               1247
#define IDC_SEP1                        1248
#define IDC_MAIN_BK_PICTURES            1249
#define IDC_SEP2                        1250
#define IDC_TASKS_RADIO_VTODO           1251
#define IDC_MAIN_ICON_STATUS_PICTURES   1252
#define IDC_NOTES_RADIO_VNOTE           1253
#define IDC_CONTACTS_CHECK_SHARED       1254
#define IDC_LOG_EDIT_NUM_LOGS           1255
#define IDC_UPDATE_STATIC_CURRENT_VERSION 1256
#define IDC_UPDATE_STATIC_AVAILABLE_VERSION 1257
#define IDC_UPDATE_STATIC_AVAILABLE     1258
#define IDC_UPDATE_UPGRADE              1259
#define IDC_UPDATE_BUTTON_UPGRADE       1260
#define IDC_TASKS_CHECK_SHARED          1261
#define IDC_NOTES_CHECK_SHARED          1262
#define IDC_LOG_STATIC_NUM              1263
#define IDC_LOG_STATIC_SIZE             1264
#define IDC_LOG_SEND                    1265
#define IDC_WELCOME_MESSAGE             1267
#define IDC_PLEASE_WAIT                 1268
#define IDC_SEPARATOR_1                 1269
#define IDC_SEPARATOR_2                 1270
#define IDC_SEPARATOR_3                 1271
#define IDC_FULLSYNC_CHECK_PICTURES     1272
#define IDC_SYNC_BUT_NOTES2             1273
#define IDC_SYNC_BUT_PICTURES           1274
#define IDC_SYNC_CHECK_PICTURES         1275
#define IDC_SEPARATOR_4                 1276
#define IDC_PICTURES_GROUP_DIRECTION    1277
#define IDC_PICTURES_STATIC_FOLDER      1278
#define IDC_PICTURES_EDIT_FOLDER        1279
#define IDC_PICTURES_BUT_SELECT         1280
#define IDC_PICTURES_GROUP_FOLDER       1281
#define IDC_PICTURES_GROUP_ADVANCED     1282
#define IDC_PICTURES_STATIC_REMOTE      1283
#define IDC_PICTURES_EDIT_REMOTE        1284
#define IDC_PICTURES_STATIC_DATAFORMAT  1285
#define IDC_PICTURES_MIME_TYPE          1286
#define IDC_PICTURES_OK                 1287
#define IDC_PICTURES_CANCEL             1288
#define IDC_PICTURES_EDIT_SYNCTYPE      1289
#define IDC_CALENDAR_DATA_FORMAT        1290
#define IDC_TASKS_DATA_FORMAT           1291
#define IDC_POPUP_TEXT                  1301
#define IDC_POWERED_BY                  1302
#define IDC_CONTACTS_EDIT_SYNCTYPE      1303
#define IDC_CALENDAR_EDIT_SYNCTYPE      1304
#define IDC_TASKS_EDIT_SYNCTYPE         1305
#define IDC_NOTES_EDIT_SYNCTYPE         1306
#define IDC_PICTURES_COMBO_SYNCTYPE     1307
#define ID_FILE_CONFIGURATION           32771
#define ID_FILE_ZZZZ                    32772
#define ID_FILE_SYNCHRONIZE             32773
#define ID_TOOLS_FULLSYNC               32774
#define ID_TOOLS_SETLOGLEVEL            32776
#define ID_VIEW_GUIDE                   32784
#define ID_HELP_UPDATESW                32785
#define ID_MENU_UPDATE_SW               32786
#define ID_HELP_RRR                     32787
#define ID_HILFE_UPDATE                 32788
#define ID_HELP_CHECKFORUPDATES         32789
#define ID_CHECK_UPDATES                32790
#define ID_HELP_UPDATES                 32791

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        423
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1308
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
