//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OutlookPlugin.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SYNC_FORM                   101
#define IDM_NULLMENU                    127
#define IDR_NULLMENU                    127
#define IDR_MAINFRAME                   128
#define IDS_SYNCTYPE1                   129
#define IDR_MAINFRAME_DISABLED          129
#define IDS_SYNCTYPE2                   130
#define IDD_FORM_LEFT                   131
#define IDS_SYNCTYPE3                   131
#define IDD_ACCOUNT                     132
#define IDS_ACCOUNT_SETTINGS            132
#define IDD_SYNC                        133
#define IDS_ACCOUNT_URL                 133
#define IDD_CONTACTS                    134
#define IDS_ACCOUNT_USERNAME            134
#define IDD_CALENDAR                    135
#define IDS_ACCOUNT_PASSWORD            135
#define IDD_TASKS                       136
#define IDS_ACCOUNT_USEPROXY            136
#define IDD_NOTES                       137
#define IDS_ACCOUNT_PROXY_AUTH          137
#define IDS_ACCOUNT_PROXY_USER          138
#define IDD_LOG                         139
#define IDS_ACCOUNT_PROXY_PASS          139
#define IDD_DIALOG1                     140
#define IDD_FULLSYNC                    140
#define IDS_OK                          140
#define IDB_BITMAP1                     141
#define IDS_CANCEL                      141
#define IDB_CHECKBOX                    142
#define IDS_ACCOUNT                     142
#define IDS_OUTLOOK_FOLDER              143
#define IDR_241                         144
#define IDS_INCLUDE_SUBFOLDERS          144
#define IDS_SELECT_FOLDER               145
#define IDS_REMOTE_NAME                 146
#define IDS_SYNC                        147
#define IDS_ENABLED                     148
#define IDS_ADVANCED_CALENDAR           149
#define IDS_DATA_FORMAT                 150
#define IDS_USE_SIF                     151
#define IDD_PROXY                       151
#define IDS_USE_VCARD                   152
#define IDS_ENCRYPTION                  153
#define IDS_ADVANCED_CONTACTS           154
#define IDS_FULLSYNC_PERFORM            155
#define IDI_ARROWS32A                   155
#define IDS_CONTACTS                    156
#define IDI_ARROWS32B                   156
#define IDS_CALENDAR                    157
#define IDS_NOTES                       158
#define IDS_TASKS                       159
#define IDS_SYNCHRONIZE                 160
#define IDS_LOG_LEVEL                   161
#define IDS_LOG_NONE                    162
#define IDI_CANCEL                      162
#define IDS_LOG_INFO                    163
#define IDI_CONTACTS                    163
#define IDS_LOG_DEBUG                   164
#define IDI_CALENDAR                    164
#define IDS_ADVANCED_NOTES              165
#define IDI_TASKS                       165
#define IDS_ADVANCED_TASKS              166
#define IDI_NOTES                       166
#define IDS_ERROR_CANNOT_CHANGE_SETTINGS 167
#define IDI_ARROWS32C                   167
#define IDS_ERROR_SET_URL               168
#define IDI_ARROWS32D                   168
#define IDS_ERROR_SET_USERNAME          169
#define IDI_CONTACTS_GREY               169
#define IDS_ERROR_SET_PASSWORD          170
#define IDI_CALENDAR_GREY               170
#define IDS_ERROR_PROXY_USERNAME        171
#define IDI_TASKS_GREY                  171
#define IDS_ERROR_PROXY_PASSWORD        172
#define IDI_NOTES_GREY                  172
#define IDS_ERROR_SET_REMOTE_NAME       173
#define IDS_ERROR_SET_OUTLOOK_FOLDER    174
#define IDS_SCHEDULER_EVERY             174
#define IDS_MINUTES                     175
#define IDS_CODE_NOSOURCE_10            176
#define IDS_CODE_SYNC_STOPPED           177
#define IDS_CODE_AUTH_EXPIRED_402       178
#define IDS_CODE_NOTFOUND_404           179
#define IDS_CODE_INVALID_CREDENTIALS_401 180
#define IDS_CODE_ERROR_CONNECT_2001     181
#define IDS_CODE_ERROR_READING_CONTENT_2002 182
#define IDS_CODE_SERVER_NOT_FOUND_2003  183
#define IDS_CODE_INTERNET_CONNECTION_MISSING_2005 184
#define IDS_CODE_NETWORK_ERROR_2007     185
#define IDS_STRING186                   186
#define IDS_ERROR_SYNC_NOT_COMPLETED    186
#define IDS_TEXT_APPOINTMENTS           187
#define IDS_TEXT_CONTACTS               188
#define IDS_TEXT_NOTES                  189
#define IDS_TEXT_TASKS                  190
#define IDS_TEXT_SENDING                191
#define IDS_TEXT_RECEIVING              192
#define IDS_TEXT_SYNC_ENDED             193
#define IDS_MAINBUT_SYNCHRONIZE         194
#define IDS_MAINBUT_CANCEL              195
#define IDS_TEXT_STARTING_SYNC          196
#define IDS_TEXT_SYNC_CANCELED          197
#define IDS_LEFTVIEW_ACCOUNT            198
#define IDS_LEFTVIEW_SYNCHRONIZATION    199
#define IDS_HOURS                       200
#define IDS_SCHEDULER_PLEASE_SET_VALUE  201
#define IDS_SCHEDULER_MIN_VALUE_IS      202
#define IDS_SCHEDULER_MAX_VALUE_IS      203
#define IDS_SCHEDULER_CANNOT_SCHEDULE   204
#define IDS_LEFTVIEW_CONTACTS           205
#define IDS_LEFTVIEW_CALENDAR           206
#define IDS_LEFTVIEW_TASKS              207
#define IDS_LEFTVIEW_NOTES              208
#define IDS_LEFTVIEW_SCHEDULER          209
#define IDS_SCHEDULER                   209
#define IDS_LEFTVIEW_LOG                210
#define IDS_DAYS                        211
#define IDS_MSG_CLOSE_SYNC_IN_PROGRESS  212
#define IDS_ABOUT_MAIN_TEXT             213
#define IDS_ABOUT_COPYRIGHT             213
#define IDS_TEXT_SYNC_ALREADY_RUNNING   214
#define IDS_SYNC_ABORTED_AVOID_FULLSYNC 215
#define IDS_TEXT_SYNC_IN_PROGRESS       216
#define IDS_DETAILS                     217
#define IDS_SYNC_SETTINGS               218
#define IDS_APPLY                       219
#define IDS_ERROR_SYNC_TERMINATED       220
#define IDS_TEXT_CANCELING_SYNC         221
#define IDS_MAIN_PRESS_TO_SYNC          222
#define IDS_MAIN_PRESS_TO_CANCEL        223
#define IDS_DONE                        224
#define IDS_SERVER                      225
#define IDS_PROXY_SETTINGS              226
#define IDS_PROXY_SETTINGS2             227
#define IDS_ITEMS                       228
#define IDS_SYNC_SYNCHRONIZE_EVERY      229
#define IDS_SECURITY                    230
#define IDS_SYNC_ENABLE_ENCRYPTION      231
#define IDS_CONTACTS_DETAILS            232
#define IDS_SYNC_DIRECTION              233
#define IDS_CONTACTS_FOLDER             234
#define IDS_CURRENT                     235
#define IDS_ADVANCED                    236
#define IDS_CALENDAR_DETAILS            237
#define IDS_CALENDAR_FOLDER             238
#define IDS_USE_VCAL                    239
#define IDS_TASKS_DETAILS               240
#define IDS_TASKS_FOLDER                241
#define IDS_NOTES_DETAILS               242
#define IDS_NOTES_FOLDER                243
#define IDS_RECOVER_PERFORMS            244
#define IDS_DIRECTION                   245
#define IDS_FULLSYNC_SYNCTYPE2          246
#define IDS_FULLSYNC_SYNCTYPE1          247
#define IDS_FULLSYNC_SYNCTYPE3          248
#define IDS_RECOVER                     249
#define IDB_BITMAP2                     249
#define IDS_LOGGING                     250
#define IDB_BITMAP3                     250
#define IDS_NOT_SYNCHRONIZED            251
#define IDS_FUNAMBOL_LINK               252
#define IDB_BITMAP4                     252
#define IDS_SYNCHRONIZED                253
#define IDS_AT                          254
#define IDS_MAIN_CALENDAR               255
#define IDI_LOGO                        255
#define IDS_MAIN_CONTACTS               256
#define IDB_BK_DARK                     256
#define IDS_MAIN_TASKS                  257
#define IDB_BK_LIGHT                    257
#define IDS_MAIN_NOTES                  258
#define IDB_BITMAP6                     258
#define IDB_BK_BLUE                     258
#define IDS_ERROR_SET_CONNECTION        259
#define IDI_SYNC                        259
#define IDS_ABOUT_TITLE                 260
#define IDI_ACCOUNT                     260
#define IDS_STRING261                   261
#define IDS_MAIN_LAST_SYNC_FAILED       261
#define IDS_MAIN_LAST_SYNC_CANCELED     262
#define IDI_SYNC_ALL                    262
#define IDS_CODE_HTTP_NOT_FOUND_404     263
#define IDS_CODE_HTTP_NOT_FOUND_2060    263
#define IDI_ALERT                       263
#define IDI_OK                          264
#define IDI_COMPLETE                    264
#define IDS_UNEXPECTED_EXCEPTION        264
#define IDS_SYNCALL                     265
#define IDI_ICON1                       265
#define IDB_BK_DARK_BLUE                266
#define IDI_SYNC_ALL_BLUE               266
#define IDS_CODE_DROPPED_ITEMS          266
#define IDS_TEXT_CHECKING               267
#define IDB_LEFT_BUTTON                 267
#define IDS_FINISHED_SENDING            268
#define IDB_SEPARATOR                   269
#define IDS_GUIDE_LINK                  269
#define IDS_ERR_SERVER_TIMOUT           270
#define IDS_CODE_SERVER_BUSY            271
#define IDS_CODE_SERVER_BUSY_SYNC       272
#define IDS_CODE_SERVER_ERROR_2052      273
#define IDS_CODE_DROPPED_ITEMS_SERVER   274
#define IDS_CODE_NO_SOURCES             275
#define IDS_HOURS2                      276
#define IDS_HOUR                        276
#define IDS_CODE_FORBIDDEN_403          277
#define IDS_USE_VTODO                   278
#define IDS_USE_VNOTE                   279
#define IDS_EVENT_FILTER                280
#define IDS_SYNC_PAST_EVENTS            281
#define IDS_DATE_FILTER_NONE            282
#define IDS_DATE_FILTER_LAST_WEEK       283
#define IDS_DATE_FILTER_LAST_MONTH      284
#define IDS_DATE_FILTER_LAST_3_MONTHS   285
#define IDS_DATE_FILTER_LAST_6_MONTHS   286
#define IDS_DATE_FILTER_ALL             287
#define IDS_DATE_FILTER_LAST_2_WEEKS    288
#define IDC_TREE1                       1005
#define IDC_SCHEDULER_SPIN              1007
#define IDC_EDIT2                       1008
#define IDC_ACCOUNT_EDIT_USERNAME       1008
#define IDC_EDIT3                       1009
#define IDC_ACCOUNT_EDIT_URL            1009
#define IDC_EDIT4                       1010
#define IDC_ACCOUNT_EDIT_PASSWORD       1010
#define IDC_CHECK1                      1011
#define IDC_FULLSYNC_CHECK_CONTACTS     1011
#define IDC_SYNC_CHECK_ENCRYPTION       1011
#define IDC_CALENDAR_STATIC_FILTER      1011
#define IDC_CHECK2                      1012
#define IDC_FULLSYNC_CHECK_CALENDAR     1012
#define IDC_EDIT5                       1013
#define IDC_CHECK3                      1013
#define IDC_FULLSYNC_CHECK_TASKS        1013
#define IDC_EDIT6                       1014
#define IDC_CHECK4                      1014
#define IDC_ACCOUNT_PROXY_PASS          1014
#define IDC_FULLSYNC_CHECK_NOTES        1014
#define IDC_BUTTON1                     1015
#define IDC_TASKS_OK                    1015
#define IDC_MAIN_BUT_SYNC               1015
#define IDC_SYNC_APPLY                  1015
#define IDC_LOG_VIEWLOG                 1015
#define IDC_ACCOUNT_BUT_PROXY           1015
#define IDC_BUTTON2                     1016
#define IDC_TASKS_CANCEL                1016
#define IDC_SYNC_DETAILS                1016
#define IDC_COMBO1                      1017
#define IDC_SCHEDULER_COMBO_VALUE_TYPE  1017
#define IDC_BUTTON7                     1017
#define IDC_BUTTON3                     1018
#define IDC_SYNC_BUT_CONTACTS           1018
#define IDC_MAIN_BUT_START              1018
#define IDC_EDIT1                       1019
#define IDC_TASKS_EDIT_FOLDER           1019
#define IDC_SCHEDULER_VALUE             1019
#define IDC_COMBO2                      1020
#define IDC_SYNC_COMBO_CALENDAR         1020
#define IDC_SCHEDULER_COMBO_VALUE       1020
#define IDC_BUTTON4                     1021
#define IDC_RADIO1                      1021
#define IDC_SYNC_BUT_CALENDAR           1021
#define IDC_LOG_RADIO_NONE              1021
#define IDC_FULLSYNC_RADIO1             1021
#define IDC_COMBO3                      1022
#define IDC_RADIO2                      1022
#define IDC_SPIN1                       1022
#define IDC_SYNC_COMBO_TASKS            1022
#define IDC_LOG_RADIO_INFO              1022
#define IDC_SYNC_STATIC_NOTES           1022
#define IDC_FULLSYNC_RADIO2             1022
#define IDC_BUTTON5                     1023
#define IDC_LIST1                       1023
#define IDC_RADIO3                      1023
#define IDC_SYNC_BUT_TASKS              1023
#define IDC_LOG_RADIO_DEBUG             1023
#define IDC_FULLSYNC_RADIO3             1023
#define IDC_LEFT_LIST                   1023
#define IDC_COMBO4                      1024
#define IDC_ACCOUNT_STATIC_ACCOUNTSETTINGS 1024
#define IDC_SYNC_COMBO_NOTES            1024
#define IDC_BUTTON6                     1025
#define IDC_ACCOUNT_BUTOK               1025
#define IDC_SYNC_BUT_NOTES              1025
#define IDC_ACCOUNT_STATIC_USERNAME     1026
#define IDC_SCHEDULER_SPIN2             1026
#define IDC_CALENDAR_COMBO_SYNCTYPE     1032
#define IDC_CALENDAR_EDIT_FOLDER        1033
#define IDC_CALENDAR_CHECK_INCLUDE      1034
#define IDC_CALENDAR_BUT_SELECT         1035
#define IDC_CALENDAR_EDIT_REMOTE        1036
#define IDC_CALENDAR_RADIO_SIF          1037
#define IDC_CALENDAR_RADIO_VCARD        1038
#define IDC_CALENDAR_COMBO_FILTER       1039
#define IDC_CONTACTS_COMBO_SYNCTYPE     1041
#define IDC_CONTACTS_EDIT_FOLDER        1042
#define IDC_CONTACTS_CHECK_INCLUDE      1043
#define IDC_CONTACTS_BUT_FOLDER         1044
#define IDC_CONTACTS_EDIT_REMOTE        1045
#define IDC_CONTACTS_RADIO_SIF          1046
#define IDC_CONTACTS_RADIO_VCARD        1047
#define IDC_NOTES_CHECK_ENABLED         1049
#define IDC_NOTES_COMBO_SYNCTYPE        1050
#define IDC_NOTES_EDIT_FOLDER           1051
#define IDC_NOTES_CHECK_INCLUDE         1052
#define IDC_NOTES_BUT_SELECT            1053
#define IDC_NOTES_EDIT_REMOTE           1054
#define IDC_NOTES_RADIO_SIF             1055
#define IDC_NOTES_RADIO_VCARD           1056
#define IDC_TASKS_COMBO_SYNCTYPE        1060
#define IDC_TASKS_CHECK_INCLUDE         1061
#define IDC_TASKS_BUT_SELECT            1062
#define IDC_TASKS_EDIT_REMOTE           1063
#define IDC_TASKS_RADIO_SIF             1064
#define IDC_TASKS_RADIO_VCARD           1065
#define IDC_SCHEDULER_CHECK_ENABLED     1067
#define IDC_SYNC_CHECK_CONTACTS         1068
#define IDC_SYNC_CHECK_CALENDAR         1069
#define IDC_SYNC_CHECK_TASKS            1070
#define IDC_SYNC_CHECK_NOTES            1071
#define IDC_SYNC_COMBO_CONTACTS         1072
#define IDC_ACCOUNT_BUT_CANCEL          1073
#define IDC_CALENDAR_BUTOK              1074
#define IDC_CALENDAR_BUTCANCEL          1075
#define IDC_CONTACTS_BUTOK              1076
#define IDC_CONTACTS_BUTCANCEL          1077
#define IDC_LOG_BUTOK                   1078
#define IDC_LOG_OK                      1078
#define IDC_LOG_CANCEL                  1079
#define IDC_NOTES_OK                    1080
#define IDC_NOTES_CANCEL                1081
#define IDC_SYNC_OK                     1084
#define IDC_SYNC_CANCEL                 1085
#define IDC_COMBOBOXEX1                 1088
#define IDC_LIST2                       1089
#define IDC_SYNC_STATIC_SETTINGS        1090
#define IDC_TASKS_STATIC_DATAFORMAT     1092
#define IDC_CALENDAR_STATIC_DATAFORMAT  1093
#define IDC_NOTES_STATIC_DATAFORMAT     1094
#define IDC_CONTACTS_STATIC_DATAFORMAT  1095
#define IDC_NOTES_STATIC_DATAFORMAT2    1095
#define IDC_NOTES_STATIC_DATAFORMAT3    1096
#define IDC_CONTACTS_DATA_FORMAT        1096
#define IDC_SYNC_PROGRESS_CONTACTS      1098
#define IDC_SYNC_PROGRESS_CALENDAR      1099
#define IDC_SYNC_PROGRESS_NOTES         1100
#define IDC_SYNC_PROGRESS_TASKS         1101
#define IDC_SYNC_STATIC_CONTACTS        1102
#define IDC_SYNC_STATIC_CALENDAR        1103
#define IDC_SYNC_STATIC_TASKS           1104
#define IDC_SYNC_ICON_CONTACTS          1105
#define IDC_SYNC_ICON_CALENDAR          1106
#define IDC_SYNC_ICON_TASKS             1107
#define IDC_SYNC_ICON_NOTES             1108
#define IDC_SCROLLBAR1                  1109
#define IDC_SYNC_PROGRESS_TOTAL         1109
#define IDC_SYNC_STATIC_TOTAL           1110
#define IDC_SYNC_ICON_TOTAL             1111
#define IDC_NOTES_ADVANCED              1112
#define IDC_ACCOUNT_STATIC_URL          1113
#define IDC_CALENDAR_STATIC_FOLDER      1115
#define IDC_CALENDAR_STATIC_REMOTE      1116
#define IDC_CONTACTS_STATIC_FOLDER      1118
#define IDC_CONTACTS_STATIC_REMOTE      1119
#define IDC_NOTES_STATIC_SYNCTYPE       1120
#define IDC_NOTES_STATIC_FOLDER         1121
#define IDC_NOTES_STATIC_REMOTE         1122
#define IDC_NOTES_STATIC_SIF            1123
#define IDC_TASKS_STATIC_SIF            1124
#define IDC_TASKS_STATIC_FOLDER         1126
#define IDC_TASKS_STATIC_REMOTE         1127
#define IDC_ABOUT_MAIN                  1129
#define IDC_ACCOUNT_APPLY               1130
#define IDC_ABOUT_LICENCE               1130
#define IDC_ABOUT_COPYRIGHT             1131
#define IDC_LOG_APPLY                   1132
#define IDC_ACCOUNT_STATIC_PASSWORD     1134
#define IDC_LOG_GROUP_LOGLEVEL          1137
#define IDC_FULLSYNC_STATIC_RECOVER     1138
#define IDC_FULLSYNC_DIRECTION          1139
#define IDC_FULLSYNC_GROUP_DIRECTION    1139
#define IDC_FULLSYNC_GROUP_ITEMS        1140
#define IDC_PROXY_ENABLE                1141
#define IDC_PROXY_AUTH                  1142
#define IDC_PROXY_EDIT_USER             1143
#define IDC_PROXY_EDIT_PASS             1144
#define IDC_PROXY_STATIC_USER           1145
#define IDC_PROXY_STATIC_PASSWORD       1146
#define IDC_ACCOUNT_GROUP_SERVER        1147
#define IDC_SCHEDULER_GROUP             1148
#define IDC_SYNC_GROUP_ITEMS            1149
#define IDC_SYNC_GROUP_SECURITY         1150
#define IDC_CONTACTS_GROUP_DIRECTION    1151
#define IDC_CONTACTS_GROUP_FOLDER       1152
#define IDC_CONTACTS_GROUP_ADVANCED     1153
#define IDC_CALENDAR_GROUP_DIRECTION    1154
#define IDC_CALENDAR_GROUP_FOLDER       1155
#define IDC_CALENDAR_GROUP_ADVANCED     1156
#define IDC_NOTES_GROUP_DIRECTION       1157
#define IDC_CALENDAR_GROUP_FILTER       1157
#define IDC_NOTES_GROUP_FOLDER          1158
#define IDC_NOTES_GROUP_ADVANCED        1159
#define IDC_TASKS_GROUP_DIRECTION       1160
#define IDC_TASKS_GROUP_FOLDER          1161
#define IDC_TASKS_ADVANCED              1162
#define IDC_MAIN_MSG_PRESS              1166
#define IDC_MAIN_ICON_CONTACTS          1168
#define IDC_MAIN_ICON_CALENDAR          1169
#define IDC_MAIN_ICON_TASKS             1170
#define IDC_MAIN_ICON_NOTES             1171
#define IDC_MAIN_STATIC_CONTACTS        1172
#define IDC_MAIN_STATIC_STATUS_CONTACTS 1173
#define IDC_MAIN_STATIC_CALENDAR        1174
#define IDC_MAIN_STATIC_STATUS_CALENDAR 1175
#define IDC_MAIN_STATIC_TASKS           1176
#define IDC_MAIN_STATIC_STATUS_TASKS    1177
#define IDC_MAIN_STATIC_STATUS_NOTES    1178
#define IDC_MAIN_STATIC_NOTES           1179
#define IDC_MAIN_GROUP_SYNC             1180
#define IDC_MAIN_GROUP_SOURCES          1181
#define IDC_MAIN_LINK_CALENDAR          1183
#define IDC_ABOUT_LINK                  1184
#define IDC_MAIN_LINK_NOTES             1186
#define IDC_MAIN_LINK_CONTACTS          1187
#define IDC_MAIN_LINK_TASKS             1188
#define IDC_STATIC1                     1190
#define IDC_MAIN_ICON_STATUS_CONTACTS   1192
#define IDC_MAIN_ICON_STATUS_CALENDAR   1193
#define IDC_MAIN_ICON_STATUS_TASKS      1194
#define IDC_MAIN_ICON_STATUS_NOTES      1195
#define IDC_MAIN_ICON_STATUS_SYNC       1196
#define IDC_MAIN_BK_SYNC                1197
#define IDC_MAIN_BK_SYNC2               1198
#define IDC_MAIN_BK_CONTACTS            1198
#define IDC_MAIN_BK_CONTACTS2           1199
#define IDC_MAIN_BK_CALENDAR            1199
#define IDC_MAIN_BK_TASKS               1200
#define IDC_RECT2                       1200
#define IDC_MAIN_BK_CALENDAR3           1201
#define IDC_MAIN_BK_NOTES               1201
#define IDC_SEP1                        1202
#define IDC_SEP2                        1203
#define IDC_TASKS_RADIO_VTODO           1203
#define IDC_NOTES_RADIO_VNOTE           1204
#define ID_FILE_CONFIGURATION           32771
#define ID_FILE_ZZZZ                    32772
#define ID_FILE_SYNCHRONIZE             32773
#define ID_TOOLS_FULLSYNC               32774
#define ID_TOOLS_SETLOGLEVEL            32776
#define ID_VIEW_GUIDE                   32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        271
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1205
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
